name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Inject environment variables
        run: |
          sed -i 's|{{TMDB_API_KEY}}|'"${{ secrets.TMDB_API_KEY }}"'|' public/template/movie-template.html
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }} # Asegúrate de que esta clave esté en Settings > Secrets
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public